version: 2
workflows:
  main:
    jobs:
      - build
  version: 2

jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01
      docker_layer_caching: true
    steps:
      - checkout
      - run:
          name: "Test"
          command: cd test && ./test.sh
